<a href="https://colab.research.google.com/github/premkumar6374710-alt/python_practice/blob/main/Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Array create (10,20,30,40,50)

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


2. arange() 1 to 10

In [2]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


3. 5 zeros array


In [3]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


4. 5 ones array

In [4]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


5. Even numbers 2 to 20

In [5]:
arr = np.arange(2, 21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


6. Number of elements

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr.size)

5


7. Shape and dimensions

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Dimensions: 2


8. 3x3 array from 1 to 9

In [8]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9. Max and min values

In [9]:
arr = np.array([15, 8, 25, 10, 30])
print("Max:", arr.max())
print("Min:", arr.min())

Max: 30
Min: 8


10. Sum and average

In [10]:
arr = np.array([10, 20, 30, 40, 50])
print("Sum:", arr.sum())
print("Average:", arr.mean())

Sum: 150
Average: 30.0


11. Index of maximum value

In [11]:
arr = np.array([15, 8, 25, 10, 30])
print(arr.argmax())

4


12. First, third, last elements

In [12]:
arr = np.array([100, 200, 300, 400, 500])
print(arr[0], arr[2], arr[-1])

100 300 500


13. Reverse the array

In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


14. First three elements (slicing)

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[:3])

[1 2 3]


15. 2x4 array, rows and columns

In [15]:
arr = np.arange(1, 9).reshape(2, 4)
print(arr)
print("Rows:", arr.shape[0])
print("Columns:", arr.shape[1])

[[1 2 3 4]
 [5 6 7 8]]
Rows: 2
Columns: 4


16. 1 to 20, extract even numbers

In [16]:
arr = np.arange(1, 21)
even = arr[arr % 2 == 0]
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


17. Replace values > 50 with 0

In [17]:
arr = np.array([10, 60, 30, 80, 40, 90])
arr[arr > 50] = 0
print(arr)

[10  0 30  0 40  0]


18. Values greater than 25

In [18]:
arr = np.array([10, 30, 15, 40, 20, 50])
print(arr[arr > 25])

[30 40 50]


19. Addition, subtraction, multiplication, division

In [19]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("Add:", a + b)
print("Sub:", a - b)
print("Mul:", a * b)
print("Div:", a / b)

Add: [11 22 33]
Sub: [ 9 18 27]
Mul: [10 40 90]
Div: [10. 10. 10.]


20. Element-wise square

In [20]:
arr = np.array([2, 4, 6, 8, 10])
print(arr ** 2)

[  4  16  36  64 100]


21. Square root of every value

In [21]:
arr = np.array([4, 9, 16, 25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


22. Mean, median, std dev, variance

In [22]:
arr = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))
print("Variance:", np.var(arr))

Mean: 30.0
Median: 30.0
Std Dev: 14.142135623730951
Variance: 200.0


23. 3x3 matrix, sum of each row

In [23]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr.sum(axis=1))

[ 6 15 24]


24. 3x3 matrix, sum of each column

In [24]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr.sum(axis=0))

[12 15 18]


25. Max value from each row (2D array)

In [25]:
arr = np.array([[10, 20, 30], [5, 50, 15]])
print(arr.max(axis=1))

[30 50]


26. Min value from each column

In [26]:
arr = np.array([[10, 20, 30], [5, 50, 15]])
print(arr.min(axis=0))

[ 5 20 15]


27. 1D array to 2x3 using reshape()

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


28. Flatten 2D array to 1D

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.flatten())

[1 2 3 4 5 6]


29. 2x2 matrix multiplication

In [29]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(np.dot(m1, m2))

[[19 22]
 [43 50]]


30. Marks analysis

In [30]:
marks = np.array([45, 78, 92, 35, 88, 67, 30, 95])
print("Above 60:", marks[marks > 60])
print("Highest:", marks.max())
print("Lowest:", marks.min())
print("Average:", marks.mean())
print("Count above 60:", (marks > 60).sum())

Above 60: [78 92 88 67 95]
Highest: 95
Lowest: 30
Average: 66.25
Count above 60: 5
